// frontend/src/components/Sidebar.svelte
<script>
  import { push, router } from 'svelte-spa-router';
  import { authStore } from '../stores/authStore.js';

  const menuItems = [
    { label: 'Profilim' , path: '/profilim'},
    { label: 'Ziyaretçiler', path: '/dashboard' },
    { label: 'Personel', path: '/personal' },
    { label: 'Rapor', path: '/reports' },
    { label: 'Kullanıcılar', path: '/users', adminOnly: true }
  ];
</script>

<aside class="w-64 bg-slate-800 text-white min-h-screen flex flex-col">
  <div class="px-6 py-5 text-lg font-bold border-b border-slate-700">
    VMS
  </div>
  <nav class="flex-1 py-4">
    {#each menuItems as item}
      {#if !item.adminOnly || $authStore.role === 'ADMIN' || $authStore.role === 'SUPER_ADMIN'}
        <button
          on:click={() => push(item.path)}
          class="w-full text-left px-6 py-3 hover:bg-slate-700 {router.location === item.path ? 'bg-slate-700 border-l-4 border-blue-500' : 'border-l-4 border-transparent'}">
          {item.label}
        </button>
      {/if}
    {/each}
  </nav>
</aside>

// frontend-react/src/components/Layout/Sidebar.tsx
import React from 'react'
import { NavLink } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'

const navItems = [
  { to: '/visitors', label: 'Ziyaretçiler', roles: ['SUPER_ADMIN', 'ADMIN', 'RECEPTIONIST'] },
  { to: '/personal', label: 'Personel', roles: ['SUPER_ADMIN', 'ADMIN', 'RECEPTIONIST'] },
  { to: '/reports', label: 'Raporlar', roles: ['SUPER_ADMIN', 'ADMIN', 'RECEPTIONIST'] },
  { to: '/users', label: 'Kullanıcılar', roles: ['SUPER_ADMIN', 'ADMIN'] },
  { to: '/profile', label: 'Profilim', roles: ['SUPER_ADMIN', 'ADMIN', 'RECEPTIONIST'] },
] as const

export function Sidebar() {
  const { user, hasRole, logout } = useAuth()

  return (
    <aside className="flex h-screen w-60 flex-col border-r border-slate-200 bg-white">
      <div className="border-b border-slate-100 px-4 py-4">
        <p className="text-sm font-semibold text-slate-800">VMS</p>
        <p className="text-xs text-slate-400">{user?.username}</p>
      </div>
      <nav className="flex-1 space-y-1 p-2">
        {navItems
          .filter((item) => hasRole(...(item.roles as any)))
          .map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              className={({ isActive }) =>
                [
                  'block rounded-md px-3 py-2 text-sm font-medium',
                  isActive ? 'bg-primary-50 text-primary-700' : 'text-slate-600 hover:bg-slate-50',
                ].join(' ')
              }
            >
              {item.label}
            </NavLink>
          ))}
      </nav>
      <div className="border-t border-slate-100 p-2">
        <button
          onClick={logout}
          className="w-full rounded-md px-3 py-2 text-left text-sm text-slate-600 hover:bg-slate-50"
        >
          Çıkış Yap
        </button>
      </div>
    </aside>
  )
}
